function [p, devices] = if_workbench_validate_profile(p,action)
%IF_WORKBENCH_VALIDATE_PROFILE Pure device selection and board preflight.
% No constructors with I/O, port discovery, queries or output changes.
devices={'awg'};
if strcmp(p.stage,'tx_if')
    assert(strcmp(p.scope.side,'lower')&&isequal(p.scope.channels,{'C2'}), ...
        'msiq:if:Wiring','TX IF requires lower C2.');
else
    assert(strcmp(p.scope.side,'upper')&&numel(p.scope.channels)==2&& ...
        numel(unique(p.scope.channels))==2&&all(ismember(p.scope.channels,{'C1','C2','C3','C4'})), ...
        'msiq:if:Wiring','Select two distinct upper scope channels C1 through C4.');
end
assert(~ismember(action,{'scan','mock','resume'}) || strcmp(p.stage,'rx_iq'), ...
    'msiq:if:Stage','Board scanning requires RX I/Q wiring.');
if ~strcmp(action,'board_set'), devices{end+1}='scope'; end
automatic=ismember(action,{'balance','scan','mock','resume','final_capture'}) && strcmp(p.stage,'rx_iq');
needsBoard=strcmp(action,'board_set') || automatic;
assert(~strcmp(action,'board_set') || ~strcmp(p.stage,'direct'), ...
    'msiq:if:Stage','Direct wiring has no board control.');
if ~needsBoard, return; end
devices{end+1}='board';
if strcmp(p.mode,'mock')
    % Explicit synthetic fixture, never inherited into live defaults.
    defaults=struct('mode','mock','initial_state_confirmed',true, ...
        'state_confirmation','synthetic mock fixture', ...
        'initial_state',struct('rf',20*ones(1,6),'i',20*ones(1,6), ...
        'q',20*ones(1,6),'agc',zeros(1,6)), ...
        'limits',struct('rf',repmat([0 31.5],6,1),'i',repmat([0 31.5],6,1), ...
        'q',repmat([0 31.5],6,1)), ...
        'mapping',struct('i_channel',p.scope.channels{1},'q_channel',p.scope.channels{end}), ...
        'runtime',struct('protocol_verified',true,'mapping_verified',true,'response_verified',true));
    defaults.initial_state.rf(p.subband)=p.initial.pre_db;
    defaults.initial_state.i(p.subband)=p.initial.i_db;
    defaults.initial_state.q(p.subband)=p.initial.q_db;
    p.board=merge(defaults,p.board);
end
b=p.board;
assert(isfield(b,'mode')&&strcmp(b.mode,p.mode), ...
    'msiq:if:BoardMode','Board transport must explicitly match the run mode.');
assert(isfield(b,'initial_state_confirmed')&&isequal(b.initial_state_confirmed,true)&& ...
    isfield(b,'state_confirmation')&&~isempty(strtrim(char(b.state_confirmation))), ...
    'msiq:if:BoardState','Explicit six-band manual state confirmation required.');
assert(isfield(b,'initial_state')&&isfield(b,'limits'), ...
    'msiq:if:BoardState','Initial board state and approved limits required.');
for key={'rf','i','q','agc'}
    name=key{1}; assert(isfield(b.initial_state,name),'msiq:if:BoardState','Missing %s state.',name);
    msiq.instruments.if_board_encode(name,b.initial_state.(name));
    if strcmp(name,'agc'), continue; end
    assert(isfield(b.limits,name),'msiq:if:BoardLimits','Missing %s limits.',name);
    lim=b.limits.(name); v=b.initial_state.(name)(:);
    assert(isnumeric(lim)&&isequal(size(lim),[6 2])&&all(isfinite(lim(:)))&& ...
        all(lim(:)>=0&lim(:)<=31.5)&&all(lim(:,1)<=lim(:,2))&& ...
        all(v>=lim(:,1)&v<=lim(:,2)), ...
        'msiq:if:BoardLimits','Initial state must lie within approved six-by-two limits.');
end
assert(isequal([b.initial_state.rf(p.subband),b.initial_state.i(p.subband),b.initial_state.q(p.subband)], ...
    [p.initial.pre_db,p.initial.i_db,p.initial.q_db]), ...
    'msiq:if:BoardState','Run initial setting differs from confirmed physical board state.');
if strcmp(p.mode,'live')
    assert(flag(b,'protocol_verified'),'msiq:if:BoardProtocol','Runtime protocol verification required.');
    assert(isfield(b,'serial'),'msiq:if:BoardSerial','Explicit serial configuration required.');
    for key={'port','baud_rate','data_bits','parity','stop_bits','flow_control','timeout','protocol_version'}
        name=key{1}; assert(isfield(b.serial,name)&&~isempty(b.serial.(name)), ...
            'msiq:if:BoardSerial','Missing serial setting %s.',name);
    end
    s=b.serial;
    assert(isnumeric(s.baud_rate)&&isscalar(s.baud_rate)&&isfinite(s.baud_rate)&& ...
        s.baud_rate>0&&s.baud_rate==round(s.baud_rate)&& ...
        isnumeric(s.timeout)&&isscalar(s.timeout)&&isfinite(s.timeout)&&s.timeout>0&& ...
        isscalar(s.data_bits)&&ismember(s.data_bits,[5 6 7 8])&& ...
        isscalar(s.stop_bits)&&ismember(s.stop_bits,[1 1.5 2])&& ...
        any(strcmpi(s.parity,{'none','odd','even','mark','space'}))&& ...
        any(strcmpi(s.flow_control,{'none','hardware','software'})), ...
        'msiq:if:BoardSerial','Invalid serial configuration.');
end
if automatic
    assert(flag(b,'protocol_verified')&&flag(b,'mapping_verified')&&flag(b,'response_verified'), ...
        'msiq:if:BoardAutomatic','Automatic board functions require three verified runtime gates.');
    assert(isfield(b,'mapping')&&isfield(b.mapping,'i_channel')&&isfield(b.mapping,'q_channel'), ...
        'msiq:if:BoardMapping','Physical I/Q attenuation-to-scope mapping required.');
    mapped={b.mapping.i_channel,b.mapping.q_channel};
    assert(numel(unique(mapped))==2&&isequal(sort(mapped),sort(p.scope.channels)), ...
        'msiq:if:BoardMapping','I/Q mapping must cover the selected two scope channels exactly.');
    assert(b.initial_state.agc(p.subband)==0,'msiq:if:AGC','Disable AGC before automatic adjustment.');
end
end
function yes=flag(b,name)
yes=isfield(b,'runtime')&&isfield(b.runtime,name)&&isequal(b.runtime.(name),true);
end
function a=merge(a,b)
for key=fieldnames(b)'
    name=key{1};
    if isfield(a,name)&&isstruct(a.(name))&&isstruct(b.(name)), a.(name)=merge(a.(name),b.(name));
    else, a.(name)=b.(name); end
end
end
