function outcome = run_iq_loopback(~, ~, ~)
%RUN_IQ_LOOPBACK Deprecated compatibility entry point.

error('msiq:loopback:Deprecated', ...
    ['Use TX_Workbench(''awg_plan'') followed by ', ...
    '''awg_apply''. The old action could globally disable AWG outputs ', ...
    'and is intentionally unavailable.']);
end
