function outcome = run_awg_off_check(cfg, condition, execution_mode)
%RUN_AWG_OFF_CHECK Execute or plan the AWG/scope-only V212 check.

if nargin < 3, execution_mode = 'hardware'; end
is_dry = strcmpi(execution_mode, 'dry_run');
addpath(fullfile(cfg.code_root, 'result_management'));
addpath(fullfile(cfg.code_root, 'plotting'));
parameters = struct('stage', 'V212', ...
    'boundary', 'M8195A electrical output to LeCroy only', ...
    'signal_generator_allowed', false);

if is_dry
    before = msiq.instruments.get_audit();
    run = msiq.bench.create_run(cfg, condition, 'v212_awg_off_check', ...
        'V212_AWG_OFF_CHECK', 'dry_run', 1, struct([]), parameters);
    try
        Result_Summary_Initialize(run, summary_columns(), summary_units());
        plan = struct('stage', 'V212', 'planned_observations', 1, ...
            'instruments', {{'M8195A','LeCroy'}}, ...
            'signal_generator_allowed', false, ...
            'required_output_state', false(1,4), ...
            'scope_settings', cfg.scope);
        Result_Atomic_Write_Json(msiq.output_path(run, 'awg_off_plan.json'), plan);
        Test_Project_Plot_Plan(msiq.output_path(run, 'overview.png'), 1, ...
            struct('Title','V212 AWG OFF dry-run', ...
            'XName','计划检查','XUnit','-', 'PlannedCount',1, ...
            'Stages',{{'接线确认','四路状态读回','强制 OFF','OFF 采集'}}));
        delta = msiq.bench.audit_delta(before, msiq.instruments.get_audit());
        if any(struct2array(delta) ~= 0)
            error('msiq:run:DryRunInstrumentAccess', ...
                'V212 dry-run attempted instrument I/O.');
        end
        Result_Update_Run_Info(run, struct( ...
            'counts', struct('planned',1,'executed',0,'succeeded',0, ...
            'failed',0,'invalid',0), ...
            'safety', struct('preflight','passed', ...
            'initial_outputs','not_accessed','shutdown','not_required', ...
            'shutdown_readback','not_required','instrument_io_delta',delta)));
        Result_Log_Stage(run, 'INFO', 'safety', ...
            'V212 dry-run used no instrument connection, query, write, or capture.');
        Result_Finalize_Run(run, 'completed', 'normal_completion', [], '');
        msiq.bench.assert_flat(run);
        outcome = struct('run_dir',run.OutputDir,'status','completed', ...
            'execution_mode','dry_run','instrument_io_delta',delta);
    catch exception
        msiq.bench.finalize_failure(run, exception, 'preflight_failed');
        rethrow(exception);
    end
    return;
end

specs = msiq.bench.instrument_specs(cfg);
gate = msiq.bench.hardware_gate(cfg, specs, 'awg_off_check');
before = msiq.instruments.get_audit();
parameters.manual_setup = gate.manual_setup;
run = msiq.bench.create_run(cfg, condition, 'v212_awg_off_check', ...
    'V212_AWG_OFF_CHECK', 'hardware', 1, ...
    msiq.bench.instrument_metadata(specs), parameters);
guard = msiq.instruments.SafetyGuard(cfg);
executed = 0;
try
    Result_Summary_Initialize(run, summary_columns(), summary_units());
    guard.Sessions.awg = msiq.instruments.open_session('awg', specs.awg);
    guard.Sessions.scope = msiq.instruments.open_session('scope', specs.scope);
    identities = struct( ...
        'awg', msiq.instruments.query_idn(guard.Sessions.awg), ...
        'scope', msiq.instruments.query_idn(guard.Sessions.scope));
    Result_Atomic_Write_Json(msiq.output_path(run, ...
        'instrument_idn.json'), identities);

    initial_state = msiq.instruments.read_awg_output_state(guard.Sessions.awg);
    msiq.instruments.set_awg_output(guard.Sessions.awg, false);
    off_state = msiq.instruments.read_awg_output_state(guard.Sessions.awg);
    Result_Atomic_Write_Json(msiq.output_path(run, 'awg_state_readback.json'), ...
        struct('initial',initial_state,'after_forced_off',off_state));
    if any(off_state)
        error('msiq:safety:AwgOffReadback', ...
            'One or more DAC outputs remained enabled after forced OFF.');
    end
    if any(initial_state)
        error('msiq:safety:InitialOutputEnabled', ...
            'V212 requires all four DAC outputs to be OFF before the check.');
    end

    scope_readback = msiq.instruments.configure_scope( ...
        guard.Sessions.scope, cfg.scope);
    Result_Atomic_Write_Json(msiq.output_path(run, ...
        'scope_readback.json'), scope_readback);
    channel = msiq.bench.scope_channel(specs.scope);
    vertical_scale = msiq.instruments.read_scope_vertical_scale( ...
        guard.Sessions.scope, channel);
    raw_off = msiq.instruments.capture_scope(guard.Sessions.scope, {channel});
    [metrics, raw_off] = msiq.bench.capture_metrics(raw_off, cfg, ...
        cfg.waveform.if_center_hz, 0.6*cfg.waveform.symbol_rate_hz, ...
        vertical_scale);
    raw_name = 'AWG_OFF_repeat01_attempt01.mat';
    save(msiq.output_path(run, raw_name), 'raw_off', '-v7.3');
    executed = 1;
    Result_Summary_Append(run, {metrics.inband_power_dbm, metrics.rms_v, ...
        metrics.peak_v, metrics.clip_fraction, vertical_scale, ...
        mat2str(initial_state), mat2str(off_state), '成功', 1, 1, ...
        char(datetime('now','Format','yyyy-MM-dd HH:mm:ss')), raw_name, '', '', ''});
    plot_metrics(run, metrics);

    shutdown_report = guard.shutdown();
    if ~isempty(shutdown_report.errors) || ~shutdown_report.awg_readback_ok
        error('msiq:safety:ShutdownReadback', ...
            'V212 shutdown did not verify all four DACs OFF.');
    end
    delta = msiq.bench.audit_delta(before, msiq.instruments.get_audit());
    if delta.source_connections ~= 0 || delta.source_queries ~= 0 || ...
            delta.source_writes ~= 0 || delta.source_closes ~= 0
        error('msiq:safety:UnexpectedSourceAccess', ...
            'V212 accessed the signal generator.');
    end
    safety = struct('preflight','passed','initial_outputs',initial_state, ...
        'shutdown','passed','shutdown_readback',shutdown_report.awg_readback, ...
        'signal_generator_access',false,'instrument_io_delta',delta);
    Result_Update_Run_Info(run, struct( ...
        'counts',struct('planned',1,'executed',1,'succeeded',1, ...
        'failed',0,'invalid',0), 'safety',safety, ...
        'parameters',struct('scope_readback',scope_readback, ...
        'awg_output_readback',struct('initial',initial_state, ...
        'after_forced_off',off_state))));
    Result_Finalize_Run(run, 'completed', 'normal_completion', [], '');
    msiq.bench.assert_flat(run);
    outcome = struct('run_dir',run.OutputDir,'status','completed', ...
        'execution_mode','hardware','initial_state',initial_state, ...
        'off_state',off_state,'shutdown',shutdown_report, ...
        'instrument_io_delta',delta);
catch exception
    shutdown_report = guard.shutdown();
    delta = msiq.bench.audit_delta(before, msiq.instruments.get_audit());
    updates = struct('counts',struct('planned',1,'executed',executed, ...
        'succeeded',0,'failed',double(executed>0),'invalid',0), ...
        'safety',struct('shutdown', ...
        status_text(isempty(shutdown_report.errors) && shutdown_report.awg_readback_ok), ...
        'shutdown_readback',shutdown_report.awg_readback, ...
        'signal_generator_access',false,'instrument_io_delta',delta));
    msiq.bench.finalize_failure(run, exception, ...
        msiq.bench.classify_stop_reason(exception), updates);
    rethrow(exception);
end
end

function plot_metrics(run, metrics)
values(1) = struct('Name','OFF 带内功率','Unit','dBm', ...
    'Values',metrics.inband_power_dbm);
values(2) = struct('Name','OFF RMS','Unit','V', 'Values',metrics.rms_v);
Test_Project_Plot_Scan_Summary(msiq.output_path(run,'overview.png'), 1, ...
    values, struct('Title','V212 AWG OFF 检查','XName','检查','XUnit','-', ...
    'PlannedCount',1,'SuccessMask',true));
end

function columns = summary_columns()
columns = {'OFF带内功率','OFF RMS','OFF峰值','削顶比例','示波器量程', ...
    '初始AWG状态','强制OFF后状态','状态','序号','attempt','采集时间', ...
    '原始数据文件','单次图片文件','错误代码','错误信息'};
end

function units = summary_units()
units = {'dBm','V','V','-','V/div','-','-','-','-','-','-', ...
    '-','-','-','-'};
end

function value = status_text(ok)
if ok, value = 'passed'; else, value = 'failed'; end
end
