[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Assert-Equal {
    param(
        [Parameter(Mandatory)]$Expected,
        [Parameter(Mandatory)]$Actual,
        [Parameter(Mandatory)][string]$Message
    )

    if ($Expected -ne $Actual) {
        throw "$Message Expected '$Expected', got '$Actual'."
    }
}

function Assert-True {
    param(
        [Parameter(Mandatory)][bool]$Condition,
        [Parameter(Mandatory)][string]$Message
    )

    if (-not $Condition) {
        throw $Message
    }
}

$testRoot = Join-Path ([System.IO.Path]::GetTempPath()) ('wiztree-summary-test-' + [guid]::NewGuid().ToString('N'))
$resolvedTestRoot = [System.IO.Path]::GetFullPath($testRoot)
$tempRoot = [System.IO.Path]::GetFullPath([System.IO.Path]::GetTempPath())
if (-not $resolvedTestRoot.StartsWith($tempRoot, [System.StringComparison]::OrdinalIgnoreCase)) {
    throw "Refusing to create a test directory outside the system temp path: $resolvedTestRoot"
}

[System.IO.Directory]::CreateDirectory($resolvedTestRoot) | Out-Null
$fixture = Join-Path $resolvedTestRoot 'wiztree.csv'
$invalidFixture = Join-Path $resolvedTestRoot 'invalid.csv'
$scriptPath = Join-Path (Split-Path $PSScriptRoot -Parent) 'Summarize-WizTreeCsv.ps1'

try {
    $content = @'
Generated by WizTree 4.31 2026-08-31
File Name,Size,Allocated,Date Modified,Attributes,Files,Folders
"C:\Alpha\",320,352,2026-08-31,16,3,1
"C:\Alpha\one.bin",60,64,2026-08-31,32,0,0
"C:\Alpha\two.bin",30,32,2026-08-31,32,0,0
"C:\Alpha\sub\",250,256,2026-08-31,16,1,0
"C:\Alpha\sub\deep.bin",250,256,2026-08-31,32,0,0
"C:\Beta\",10,16,2026-08-31,16,1,0
"C:\Beta\item.txt",10,16,2026-08-31,32,0,0
'@
    [System.IO.File]::WriteAllText($fixture, $content, [System.Text.UTF8Encoding]::new($false))

    $summary = & $scriptPath -CsvPath $fixture -Roots @('C:\Alpha', 'C:\Missing') -Top 2
    $alpha = @($summary.Roots | Where-Object Root -ieq 'C:\Alpha')[0]
    $missing = @($summary.Roots | Where-Object Root -ieq 'C:\Missing')[0]

    Assert-Equal -Expected 3 -Actual $alpha.DirectItems -Message 'Direct child count is incorrect.'
    Assert-Equal -Expected 352 -Actual $alpha.AllocatedBytes -Message 'Allocated byte total is incorrect.'
    Assert-Equal -Expected 2 -Actual $alpha.Top.Count -Message 'Top limit was not applied.'
    Assert-Equal -Expected 'sub' -Actual $alpha.Top[0].Name -Message 'Top item ordering is incorrect.'
    Assert-Equal -Expected 0 -Actual $missing.DirectItems -Message 'Missing roots must return an empty summary.'
    Assert-True -Condition (-not ($alpha.Top.Path -contains 'C:\Alpha\sub\deep.bin')) -Message 'A grandchild was counted as a direct child.'

    [System.IO.File]::WriteAllText($invalidFixture, "not a WizTree export`nFile Name,Size,Allocated", [System.Text.UTF8Encoding]::new($false))
    $invalidRejected = $false
    try {
        & $scriptPath -CsvPath $invalidFixture -Roots @('C:\Alpha') | Out-Null
    }
    catch {
        $invalidRejected = $_.Exception.Message -match 'does not identify a WizTree export'
    }
    Assert-True -Condition $invalidRejected -Message 'An invalid WizTree banner was not rejected.'

    'PASS: Summarize-WizTreeCsv.ps1'
}
finally {
    if (Test-Path -LiteralPath $resolvedTestRoot) {
        Remove-Item -LiteralPath $resolvedTestRoot -Recurse -Force
    }
}
