function readback = configure_scope(session, scope_cfg)
%CONFIGURE_SCOPE Set and read back the fixed LeCroy preprocessing baseline.

channels = {'C1','C2','C3','C4'};
if isfield(session.specification, 'channels') && ...
        ~isempty(session.specification.channels)
    channels = cellstr(string(session.specification.channels));
end
readback = repmat(struct('channel', '', 'interpolation', '', ...
    'average_sweeps', NaN, 'enhance_resolution', '', ...
    'optimize_group_delay', '', 'offset_v', NaN, ...
    'vertical_scale_v_per_div', NaN), ...
    1, numel(channels));
for k = 1:numel(channels)
    channel = upper(channels{k});
    msiq.instruments.write_scpi(session, sprintf( ...
        'VBS ''app.Acquisition.%s.InterpolateType = "%s"''', ...
        channel, scope_cfg.interpolation));
    msiq.instruments.write_scpi(session, sprintf( ...
        'VBS ''app.Acquisition.%s.AverageSweeps = %d''', ...
        channel, scope_cfg.average_sweeps));
    msiq.instruments.write_scpi(session, sprintf( ...
        'VBS ''app.Acquisition.%s.EnhanceResType = "%s"''', ...
        channel, scope_cfg.enhance_resolution));
    msiq.instruments.write_scpi(session, sprintf( ...
        'VBS ''app.Acquisition.%s.OptimizeGroupDelay = "%s"''', ...
        channel, scope_cfg.optimize_group_delay));
    msiq.instruments.write_scpi(session, sprintf( ...
        'VBS ''app.Acquisition.%s.VerOffset = %.15g''', ...
        channel, scope_cfg.offset_v));

    readback(k).channel = channel;
    if session.mock
        readback(k).interpolation = scope_cfg.interpolation;
        readback(k).average_sweeps = scope_cfg.average_sweeps;
        readback(k).enhance_resolution = scope_cfg.enhance_resolution;
        readback(k).optimize_group_delay = scope_cfg.optimize_group_delay;
        readback(k).offset_v = scope_cfg.offset_v;
        if isfield(session.specification, 'mock_vertical_scale_v_per_div')
            readback(k).vertical_scale_v_per_div = double( ...
                session.specification.mock_vertical_scale_v_per_div);
        end
    else
        readback(k).interpolation = vbs_query(session, channel, 'InterpolateType');
        readback(k).average_sweeps = str2double( ...
            vbs_query(session, channel, 'AverageSweeps'));
        readback(k).enhance_resolution = vbs_query( ...
            session, channel, 'EnhanceResType');
        readback(k).optimize_group_delay = vbs_query( ...
            session, channel, 'OptimizeGroupDelay');
        readback(k).offset_v = str2double( ...
            vbs_query(session, channel, 'VerOffset'));
        readback(k).vertical_scale_v_per_div = str2double( ...
            vbs_query(session, channel, 'VerScale'));
    end
end

if scope_cfg.readback_required
    for k = 1:numel(readback)
        ok = strcmpi(strtrim(readback(k).interpolation), scope_cfg.interpolation) && ...
            readback(k).average_sweeps == scope_cfg.average_sweeps && ...
            strcmpi(strtrim(readback(k).enhance_resolution), ...
                scope_cfg.enhance_resolution) && ...
            strcmpi(strtrim(readback(k).optimize_group_delay), ...
                scope_cfg.optimize_group_delay) && ...
            isfinite(readback(k).offset_v) && ...
            abs(readback(k).offset_v-scope_cfg.offset_v) <= ...
                max(1e-15,1e-9*max(abs([readback(k).offset_v,scope_cfg.offset_v]))) && ...
            isfinite(readback(k).vertical_scale_v_per_div) && ...
            readback(k).vertical_scale_v_per_div > 0;
        if ~ok
            error('msiq:instrument:ScopeReadbackMismatch', ...
                'LeCroy preprocessing readback mismatch on %s.', ...
                readback(k).channel);
        end
    end
end
end

function value = vbs_query(session, channel, property)
command = sprintf(['VBS? ''return=app.Acquisition.%s.%s'''], ...
    channel, property);
value = strtrim(msiq.instruments.query_scpi(session, command));
value = regexprep(value, '^.*return=', '');
value = strrep(value, '"', '');
value = regexprep(value, '(?i)^VBS\s+', '');
end
