function p = if_workbench_config(overrides)
%IF_WORKBENCH_CONFIG Shared profile; unknown live limits deliberately remain NaN.
if nargin < 1, overrides=struct(); end
p = struct('schema_version',1,'mode','mock','stage','rx_iq', ...
    'mock_fixture_applied',false, ...
    'subband',1,'reference_bundle','','authorized_devices',{{}}, ...
    'wiring',struct('id','','confirmed_at','','photo_index','','notes',''), ...
    'scan',struct('pre_start_db',NaN,'pre_stop_db',NaN,'pre_step_db',NaN, ...
    'post_start_db',NaN,'post_stop_db',NaN,'post_step_db',NaN), ...
    'initial',struct('pre_db',NaN,'i_db',NaN,'q_db',NaN), ...
    'scope',struct('channels',{{'C3','C4'}},'side','upper', ...
    'sample_rate_hz',40e9,'window_s',25e-6,'vdiv',[NaN NaN], ...
    'ranges_vdiv',[],'headroom',NaN,'max_adjustments',NaN, ...
    'sample_rate_tolerance',NaN,'window_tolerance',NaN, ...
    'fresh',struct('verified',false,'reset_command','','start_command','', ...
    'completion_query','','pending_response','','complete_response','', ...
    'timeout_s',NaN,'poll_s',NaN)), ...
    'policy',struct('settle_s',NaN,'balance_tolerance_db',NaN, ...
    'balance_step_db',NaN,'max_balance_adjustments',NaN, ...
    'ber_degradation',NaN,'mer_degradation_db',NaN, ...
    'ber_recovery',NaN,'mer_recovery_db',NaN,'range_jump_db',NaN), ...
    'comparison',struct('power_tolerance_db',NaN,'max_adjustments',NaN, ...
    'amplitude_bounds_vpp',[NaN NaN],'initial_vpp',[.2 .2], ...
    'mer_advantage_db',NaN,'ber_advantage',NaN), ...
    'board',struct(),'tx_options',struct(), ...
    'mock',struct('degrade_below_post_db',-Inf,'fail_capture',Inf, ...
    'fail_shutdown',false, ...
    'fail_save',Inf,'cancel_capture',Inf,'invalid_capture',Inf, ...
    'gain_db',[1 0],'range_jump_db',0,'stale_capture',false));
p = merge(p,overrides);
% Fixture defaults are installed ONLY for mock. They are never live defaults.
if strcmp(p.mode,'mock')
    p.mock_fixture_applied=true;
    p = fill(p, 'initial',struct('pre_db',20,'i_db',20,'q_db',20));
    p = fill(p, 'scope',struct('vdiv',[.1 .1],'ranges_vdiv',[.02 .05 .1 .2 .5 1], ...
        'headroom',.8,'max_adjustments',4,'sample_rate_tolerance',.01,'window_tolerance',.01));
    p = fill(p, 'policy',struct('settle_s',0,'balance_tolerance_db',.3, ...
        'balance_step_db',.5,'max_balance_adjustments',8,'ber_degradation',1e-4, ...
        'mer_degradation_db',1,'ber_recovery',1e-4,'mer_recovery_db',1,'range_jump_db',2));
    p = fill(p, 'comparison',struct('power_tolerance_db',.2,'max_adjustments',4, ...
        'amplitude_bounds_vpp',[.05 .5]));
end
if strcmp(p.stage,'tx_if'), p.scope.channels={'C2'}; p.scope.side='lower'; end
end
function p=fill(p,section,values)
names=fieldnames(values);
for k=1:numel(names)
    n=names{k}; v=p.(section).(n);
    if isempty(v) || (isnumeric(v)&&all(isnan(v(:)))), p.(section).(n)=values.(n); end
end
end
function s=merge(s,t)
names=fieldnames(t);
for k=1:numel(names)
    n=names{k};
    if isfield(s,n)&&isstruct(s.(n))&&isstruct(t.(n)), s.(n)=merge(s.(n),t.(n));
    else, s.(n)=t.(n); end
end
end
