function outcome = run_single_dac_smoke(cfg, condition, execution_mode)
%RUN_SINGLE_DAC_SMOKE Plan or execute the AWG/scope-only V213 sequence.

if nargin < 3, execution_mode = 'hardware'; end
is_dry = strcmpi(execution_mode, 'dry_run');
addpath(fullfile(cfg.code_root, 'result_management'));
addpath(fullfile(cfg.code_root, 'plotting'));
run_cfg = msiq.apply_condition(cfg, condition);
if ~strcmpi(run_cfg.waveform.architecture, 'dual_iq_mimo')
    error('msiq:bench:SmokeRequiresDualWaveform', ...
        'V213 uses dual_iq_mimo so all four DAC components are meaningful.');
end
[tone, waveforms, tx_ref, plan] = build_sources(run_cfg, condition);
parameters = struct('stage','V213', ...
    'boundary','M8195A electrical output to LeCroy only', ...
    'signal_generator_allowed',false, ...
    'waveform_id',tx_ref.waveform_id, ...
    'tx_reference_hash',tx_ref.reference_hash_sha256, ...
    'smoke_plan',plan);

if is_dry
    before = msiq.instruments.get_audit();
    run = msiq.bench.create_run(run_cfg, condition, ...
        'v213_single_dac_smoke', 'V213_SINGLE_DAC_SMOKE', ...
        'dry_run', 2*numel(plan), struct([]), parameters);
    try
        Result_Summary_Initialize(run, summary_columns(), summary_units(), ...
            struct('DisplayColumns',{{'序号','DAC','波形阶段','采集阶段', ...
            'OFF带内功率','ON带内功率','On/Off Ratio','状态'}}, ...
            'Formats',summary_formats()));
        save_sources(run, tone, waveforms, tx_ref);
        Result_Atomic_Write_Json(msiq.output_path(run, 'smoke_plan.json'), plan);
        Test_Project_Plot_Plan(msiq.output_path(run,'overview.png'), ...
            (1:numel(plan)).', struct('Title','V213 single-DAC smoke dry-run', ...
            'XName','DAC/波形级','XUnit','-', 'PlannedCount',numel(plan), ...
            'Stages',{{'全 OFF','下载','OFF 采集','单路 ON','ON 采集','全 OFF'}}));
        delta = msiq.bench.audit_delta(before, msiq.instruments.get_audit());
        if any(struct2array(delta) ~= 0)
            error('msiq:run:DryRunInstrumentAccess', ...
                'V213 dry-run attempted instrument I/O.');
        end
        Result_Update_Run_Info(run, struct( ...
            'counts',struct('planned',2*numel(plan),'executed',0, ...
            'succeeded',0,'failed',0,'invalid',0), ...
            'inputs',{{struct('waveform_id',tx_ref.waveform_id, ...
            'tx_reference_hash',tx_ref.reference_hash_sha256)}}, ...
            'safety',struct('preflight','passed', ...
            'initial_outputs','not_accessed','shutdown','not_required', ...
            'shutdown_readback','not_required','signal_generator_access',false, ...
            'instrument_io_delta',delta)));
        Result_Log_Stage(run, 'INFO', 'safety', ...
            'V213 dry-run used no instrument connection, query, write, or capture.');
        Result_Finalize_Run(run, 'completed', 'normal_completion', [], '');
        msiq.bench.assert_flat(run);
        outcome = struct('run_dir',run.OutputDir,'status','completed', ...
            'execution_mode','dry_run','plan',plan,'instrument_io_delta',delta);
    catch exception
        msiq.bench.finalize_failure(run, exception, 'preflight_failed');
        rethrow(exception);
    end
    return;
end

specs = msiq.bench.instrument_specs(run_cfg);
gate = msiq.bench.hardware_gate(run_cfg, specs, 'single_dac_smoke');
for k = 1:numel(plan)
    plan(k).amplitude_vpp = gate.smoke_amplitude_vpp(plan(k).dac);
end
parameters.smoke_plan = plan;
parameters.manual_setup = gate.manual_setup;
before = msiq.instruments.get_audit();
run = msiq.bench.create_run(run_cfg, condition, ...
    'v213_single_dac_smoke', 'V213_SINGLE_DAC_SMOKE', ...
    'hardware', 2*numel(plan), msiq.bench.instrument_metadata(specs), parameters);
guard = msiq.instruments.SafetyGuard(run_cfg);
executed = 0;
succeeded = 0;
failed = 0;
acquisition_pending = false;
capture_stage = '';
download_reports = struct([]);
state_records = repmat(empty_state_record(), 0, 1);
spectrum_records = repmat(struct('label','','raw',struct(), ...
    'ratio_db',NaN,'rms_v',NaN,'peak_v',NaN), 0, 1);
try
    Result_Summary_Initialize(run, summary_columns(), summary_units(), ...
        struct('DisplayColumns',{{'序号','DAC','波形阶段','采集阶段', ...
        'OFF带内功率','ON带内功率','On/Off Ratio','状态'}}, ...
        'Formats',summary_formats()));
    save_sources(run, tone, waveforms, tx_ref);
    Result_Atomic_Write_Json(msiq.output_path(run, 'smoke_plan.json'), plan);
    guard.Sessions.awg = msiq.instruments.open_session('awg', specs.awg);
    guard.Sessions.scope = msiq.instruments.open_session('scope', specs.scope);
    identities = struct( ...
        'awg',msiq.instruments.query_idn(guard.Sessions.awg), ...
        'scope',msiq.instruments.query_idn(guard.Sessions.scope));
    Result_Atomic_Write_Json(msiq.output_path(run, ...
        'instrument_idn.json'), identities);

    initial_state = msiq.instruments.read_awg_output_state(guard.Sessions.awg);
    msiq.instruments.set_awg_output(guard.Sessions.awg, false);
    forced_off_state = msiq.instruments.read_awg_output_state(guard.Sessions.awg);
    if any(forced_off_state)
        error('msiq:safety:AwgOffReadback', ...
            'One or more DAC outputs remained enabled after forced OFF.');
    end
    if any(initial_state)
        error('msiq:safety:InitialOutputEnabled', ...
            'V213 requires all four DAC outputs OFF before the first stage.');
    end
    scope_readback = msiq.instruments.configure_scope( ...
        guard.Sessions.scope, run_cfg.scope);
    Result_Atomic_Write_Json(msiq.output_path(run, ...
        'scope_readback.json'), scope_readback);
    channel = msiq.bench.scope_channel(specs.scope);

    for sequence = 1:numel(plan)
        item = plan(sequence);
        try
            samples = source_samples(item, tone, waveforms);
            msiq.instruments.set_awg_output(guard.Sessions.awg, false);
            before_download = msiq.instruments.read_awg_output_state( ...
                guard.Sessions.awg);
            assert_state(before_download, false(1,4), 'before download');
            report = msiq.instruments.download_awg_single_dac( ...
                guard.Sessions.awg, samples, waveforms.awg_sample_rate_hz, ...
                item.dac, item.amplitude_vpp, 0, run_cfg);
            if isempty(download_reports)
                download_reports = report;
            else
                download_reports(end+1) = report; %#ok<AGROW>
            end
            after_download = msiq.instruments.read_awg_output_state( ...
                guard.Sessions.awg);
            assert_state(after_download, false(1,4), 'after download');

            off_scale = msiq.instruments.read_scope_vertical_scale( ...
                guard.Sessions.scope, channel);
            executed = executed+1;
            acquisition_pending = true;
            capture_stage = 'OFF';
            raw_off = msiq.instruments.capture_scope( ...
                guard.Sessions.scope, {channel});
            [off_metrics, raw_off] = msiq.bench.capture_metrics( ...
                raw_off, run_cfg, item.center_hz, item.half_width_hz, off_scale);
            off_name = sprintf('OFF_DAC%d_%s_repeat01_attempt01.mat', ...
                item.dac, item.waveform_stage);
            stage_meta = item;
            save(msiq.output_path(run, off_name), ...
                'raw_off', 'stage_meta', '-v7.3');
            off_row = cell(1,numel(summary_columns()));
            off_row(:) = {''};
            off_row([1 4 7 8 13 14 17 18 19 20 22 26]) = ...
                {off_metrics.inband_power_dbm,off_metrics.rms_v, ...
                off_metrics.clip_fraction,off_scale,item.dac,item.waveform_stage, ...
                executed,'成功',1,1,off_name,'OFF'};
            Result_Summary_Append(run,off_row);
            succeeded = succeeded+1;
            acquisition_pending = false;

            msiq.instruments.set_awg_channel_output( ...
                guard.Sessions.awg, item.dac, true);
            on_state = msiq.instruments.read_awg_output_state( ...
                guard.Sessions.awg);
            expected_on = false(1,4);
            expected_on(item.dac) = true;
            assert_state(on_state, expected_on, 'single-DAC ON');
            on_scale = msiq.instruments.read_scope_vertical_scale( ...
                guard.Sessions.scope, channel);
            assert_same_scale(off_scale, on_scale);
            executed = executed+1;
            acquisition_pending = true;
            capture_stage = 'ON';
            raw_on = msiq.instruments.capture_scope( ...
                guard.Sessions.scope, {channel});
            [on_metrics, raw_on] = msiq.bench.capture_metrics( ...
                raw_on, run_cfg, item.center_hz, item.half_width_hz, on_scale);
            on_name = sprintf('ON_DAC%d_%s_repeat01_attempt01.mat', ...
                item.dac, item.waveform_stage);
            save(msiq.output_path(run, on_name), ...
                'raw_on', 'stage_meta', '-v7.3');

            msiq.instruments.set_awg_output(guard.Sessions.awg, false);
            final_state = msiq.instruments.read_awg_output_state( ...
                guard.Sessions.awg);
            assert_state(final_state, false(1,4), 'stage shutdown');
            if ~isfinite(on_metrics.clip_fraction) || on_metrics.clip_fraction > 0
                error('msiq:safety:SmokeClipping', ...
                    'DAC%d %s capture clipped or had no valid clipping aperture.', ...
                    item.dac, item.waveform_stage);
            end

            ratio = on_metrics.inband_power_dbm-off_metrics.inband_power_dbm;
            Result_Summary_Append(run, {off_metrics.inband_power_dbm, ...
                on_metrics.inband_power_dbm, ratio, off_metrics.rms_v, ...
                on_metrics.rms_v, on_metrics.peak_v, ...
                on_metrics.clip_fraction, off_scale, on_scale, ...
                mat2str(after_download), mat2str(on_state), ...
                mat2str(final_state), item.dac, item.waveform_stage, ...
                item.waveform_sha256, off_name, executed, '成功', 1, 1, ...
                char(datetime('now','Format','yyyy-MM-dd HH:mm:ss')), ...
                on_name, '', '', '', 'ON'});
            succeeded = succeeded + 1;
            acquisition_pending = false;
            state_records(end+1) = struct('sequence',sequence, ...
                'dac',item.dac,'waveform_stage',item.waveform_stage, ...
                'after_download',after_download,'on',on_state, ...
                'after_stage',final_state); %#ok<AGROW>
            spectrum_records(end+1) = struct('label',sprintf( ...
                'DAC%d %s',item.dac,item.waveform_stage), ...
                'raw',raw_on,'ratio_db',ratio, ...
                'rms_v',on_metrics.rms_v,'peak_v',on_metrics.peak_v); %#ok<AGROW>
        catch stage_exception
            diagnostic_name = sprintf( ...
                'FAILED_DAC%d_%s_repeat01_attempt01_diagnostic.mat', ...
                item.dac, item.waveform_stage);
            save(msiq.output_path(run, diagnostic_name), ...
                'stage_exception', 'item');
            if acquisition_pending
                failed = failed+1;
                acquisition_pending = false;
                row = failure_row(item, executed, stage_exception, diagnostic_name);
                row{26} = capture_stage;
                Result_Summary_Append(run,row);
            end
            rethrow(stage_exception);
        end
    end

    Result_Atomic_Write_Json(msiq.output_path(run, ...
        'awg_download_report.json'), download_reports);
    Result_Atomic_Write_Json(msiq.output_path(run, ...
        'awg_state_readback.json'), struct('initial',initial_state, ...
        'after_forced_off',forced_off_state,'stages',state_records));
    plot_overview(run, spectrum_records, numel(plan));
    msiq.bench.plot_smoke_spectra(msiq.output_path(run, ...
        'spectrum_overview.png'), spectrum_records);

    shutdown_report = guard.shutdown();
    if ~isempty(shutdown_report.errors) || ~shutdown_report.awg_readback_ok
        error('msiq:safety:ShutdownReadback', ...
            'V213 shutdown did not verify all four DACs OFF.');
    end
    delta = msiq.bench.audit_delta(before, msiq.instruments.get_audit());
    if delta.source_connections ~= 0 || delta.source_queries ~= 0 || ...
            delta.source_writes ~= 0 || delta.source_closes ~= 0
        error('msiq:safety:UnexpectedSourceAccess', ...
            'V213 accessed the signal generator.');
    end
    if delta.multi_output_events ~= 0
        error('msiq:safety:MultipleDacOutputs', ...
            'V213 enabled more than one DAC at the same time.');
    end
    maximum_simultaneous_dacs = max(arrayfun( ...
        @(x) nnz(x.on), state_records));
    safety = struct('preflight','passed','initial_outputs',initial_state, ...
        'shutdown','passed','shutdown_readback',shutdown_report.awg_readback, ...
        'signal_generator_access',false, ...
        'maximum_simultaneous_dacs',maximum_simultaneous_dacs, ...
        'instrument_io_delta',delta);
    Result_Update_Run_Info(run, struct( ...
        'counts',struct('planned',2*numel(plan),'executed',executed, ...
        'succeeded',succeeded,'failed',failed,'invalid',0), ...
        'inputs',{{struct('waveform_id',tx_ref.waveform_id, ...
        'tx_reference_hash',tx_ref.reference_hash_sha256)}}, ...
        'safety',safety,'parameters',struct( ...
        'scope_readback',scope_readback,'smoke_plan',plan)));
    Result_Finalize_Run(run, 'completed', 'normal_completion', [], '');
    msiq.bench.assert_flat(run);
    outcome = struct('run_dir',run.OutputDir,'status','completed', ...
        'execution_mode','hardware','stage_count',numel(plan), ...
        'shutdown',shutdown_report,'instrument_io_delta',delta, ...
        'state_records',state_records);
catch exception
    shutdown_report = guard.shutdown();
    delta = msiq.bench.audit_delta(before, msiq.instruments.get_audit());
    failed = failed+double(acquisition_pending);
    updates = struct('counts',struct('planned',2*numel(plan), ...
        'executed',executed,'succeeded',succeeded, ...
        'failed',failed,'invalid',0), ...
        'safety',struct('shutdown', ...
        status_text(isempty(shutdown_report.errors) && shutdown_report.awg_readback_ok), ...
        'shutdown_readback',shutdown_report.awg_readback, ...
        'signal_generator_access',false,'instrument_io_delta',delta));
    msiq.bench.finalize_failure(run, exception, ...
        msiq.bench.classify_stop_reason(exception), updates);
    rethrow(exception);
end
end

function [tone, waveforms, tx_ref, plan] = build_sources(cfg, condition)
[waveforms, tx_ref] = msiq.generate_waveforms( ...
    cfg, condition.repeat_plan(1).seed);
preflight = msiq.preflight_waveform(waveforms, cfg, cfg.awg.model);
if ~preflight.ok
    error('msiq:bench:WaveformPreflight', ...
        'V213 V2 waveform failed preflight: %s.', preflight.reason);
end
sample_count = cfg.awg.smoke_tone_samples;
bin = round(cfg.waveform.if_center_hz/waveforms.awg_sample_rate_hz*sample_count);
tone_frequency = bin/sample_count*waveforms.awg_sample_rate_hz;
index = (0:sample_count-1).';
tone = cfg.waveform.peak_scale*sin(2*pi*bin*index/sample_count);
plan = repmat(struct('sequence',0,'dac',0,'dac_mapping','', ...
    'waveform_stage','','sample_count',0,'center_hz',0, ...
    'half_width_hz',0,'waveform_sha256','', ...
    'amplitude_vpp',NaN), 0, 1);
sequence = 0;
for dac = 1:4
    sequence = sequence + 1;
    plan(end+1) = make_item(sequence,dac,cfg.awg.dac_mapping{dac}, ...
        'tone',tone,tone_frequency,max(waveforms.awg_sample_rate_hz/sample_count*3,1e6)); %#ok<AGROW>
    sequence = sequence + 1;
    component = waveforms.awg_dac_data(:,dac);
    plan(end+1) = make_item(sequence,dac,cfg.awg.dac_mapping{dac}, ...
        'v2_component',component,cfg.waveform.if_center_hz, ...
        0.6*cfg.waveform.symbol_rate_hz); %#ok<AGROW>
end
end

function item = make_item(sequence,dac,mapping,stage,samples,center,half_width)
item = struct('sequence',sequence,'dac',dac,'dac_mapping',mapping, ...
    'waveform_stage',stage,'sample_count',numel(samples), ...
    'center_hz',center,'half_width_hz',half_width, ...
    'waveform_sha256',msiq.sha256_bytes(double(samples(:))), ...
    'amplitude_vpp',NaN);
end

function samples = source_samples(item, tone, waveforms)
if strcmp(item.waveform_stage, 'tone')
    samples = tone;
else
    samples = waveforms.awg_dac_data(:,item.dac);
end
end

function save_sources(run, tone, waveforms, tx_ref)
v2_components = waveforms.awg_dac_data;
awg_sample_rate_hz = waveforms.awg_sample_rate_hz;
save(msiq.output_path(run,'smoke_waveform_sources.mat'), ...
    'tone','v2_components','awg_sample_rate_hz','-v7.3');
save(msiq.output_path(run,'smoke_tx_reference.mat'), 'tx_ref','-v7.3');
end

function assert_state(actual, expected, stage)
if ~isequal(logical(actual), logical(expected))
    error('msiq:instrument:AwgReadbackMismatch', ...
        'AWG output readback mismatch %s: got %s, expected %s.', ...
        stage, mat2str(actual), mat2str(expected));
end
end

function assert_same_scale(first, second)
tolerance = max(1e-15, 1e-9*max(abs([first,second])));
if ~isfinite(first) || ~isfinite(second) || abs(first-second) > tolerance
    error('msiq:instrument:ScopeScaleChanged', ...
        'LeCroy V/div changed between paired OFF/ON captures.');
end
end

function plot_overview(run, records, planned_count)
count = numel(records);
ratios = [records.ratio_db].';
rms_values = [records.rms_v].';
peaks = [records.peak_v].';
metrics(1) = struct('Name','On/Off Ratio','Unit','dB','Values',ratios);
metrics(2) = struct('Name','ON RMS','Unit','V','Values',rms_values);
metrics(3) = struct('Name','ON 峰值','Unit','V','Values',peaks);
Test_Project_Plot_Scan_Summary(msiq.output_path(run,'overview.png'), ...
    (1:count).', metrics, struct('Title','V213 单 DAC 两级 smoke', ...
    'XName','DAC/波形级','XUnit','-', 'PlannedCount',planned_count, ...
    'SuccessMask',true(count,1)));
end

function row = failure_row(item, sequence, exception, diagnostic_name)
row = cell(1,numel(summary_columns()));
row(:) = {''};
row{13} = item.dac;
row{14} = item.waveform_stage;
row{15} = item.waveform_sha256;
row{17} = sequence;
row{18} = '失败';
row{19} = 1;
row{20} = 1;
row{21} = char(datetime('now','Format','yyyy-MM-dd HH:mm:ss'));
row{22} = diagnostic_name;
row{24} = exception.identifier;
row{25} = exception.message;
end

function columns = summary_columns()
columns = {'OFF带内功率','ON带内功率','On/Off Ratio','OFF RMS', ...
    'ON RMS','ON峰值','削顶比例','OFF量程','ON量程','下载后AWG状态', ...
    'ON状态','收尾状态','DAC','波形阶段','波形SHA256','OFF原始数据文件', ...
    '序号','状态','repeat','attempt','采集时间','原始数据文件', ...
    '单次图片文件','错误代码','错误信息','采集阶段'};
end

function units = summary_units()
units = {'dBm','dBm','dB','V','V','V','-','V/div','V/div','-', ...
    '-','-','-','-','-','-','-','-','-','-','-','-','-','-','-','-'};
end

function formats = summary_formats()
formats = struct();
for name = {'OFF量程','ON量程'}
    formats.(matlab.lang.makeValidName(name{1})) = 'exact';
end
end

function record = empty_state_record()
record = struct('sequence',0,'dac',0,'waveform_stage','', ...
    'after_download',false(1,4),'on',false(1,4), ...
    'after_stage',false(1,4));
end

function value = status_text(ok)
if ok, value = 'passed'; else, value = 'failed'; end
end
