function run = create_run(cfg, condition, test_name, name_part, ...
        execution_mode, planned_count, instruments, parameters)
%CREATE_RUN Create one flat V212/V213 validation run.

is_dry = strcmpi(execution_mode, 'dry_run');
if is_dry
    run_kind = 'dry_run';
    planned_kind = 'single_point';
else
    run_kind = 'single_point';
    planned_kind = '';
    execution_mode = 'hardware';
end
parameters.condition = condition;
parameters.scope_settings = cfg.scope;
create_cfg = struct( ...
    'ProjectRoot', cfg.project_root, 'ResultsRoot', cfg.results_root, ...
    'RunType', run_kind, 'NameParts', {{name_part}}, ...
    'ProjectName', 'multistream_iq_SC', 'TestName', test_name, ...
    'PlannedRunKind', planned_kind, 'RunPurpose', 'validation', ...
    'ExecutionMode', execution_mode, 'EntryPoint', 'Multistream_Workbench.m', ...
    'Parameters', parameters, 'Counts', struct('planned', planned_count), ...
    'Instruments', instruments, 'Safety', struct( ...
    'preflight', 'pending', 'initial_outputs', 'pending', ...
    'shutdown', 'pending', 'shutdown_readback', 'pending'));
run = Result_Create_Run(create_cfg);
end
