function Test_Project_Apply_Axes_Style(ax, style)
%TEST_PROJECT_APPLY_AXES_STYLE Apply shared styling without changing root defaults.

if nargin < 2 || isempty(style)
    style = Test_Project_Plot_Style();
end

set(ax, ...
    'FontName', style.FontName, ...
    'FontSize', style.FontSize, ...
    'LineWidth', style.AxisLineWidth, ...
    'Box', 'on', ...
    'Color', style.FigureColor, ...
    'TickDir', 'out', ...
    'Layer', 'top', ...
    'XGrid', 'on', ...
    'YGrid', 'on', ...
    'GridAlpha', style.GridAlpha, ...
    'MinorGridAlpha', style.MinorGridAlpha);
end
